server:
  port: 1806

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth_route
            uri: ${AUTH_ROUTE_URI:http://localhost:2504}
            predicates:
              - Path=/api/v1/auth/**
          - id: user_route
            uri: ${USER_ROUTE_URI:http://localhost:1703}
            predicates:
              - Path=/api/v1/user/**
feign:
    auth:
      name: auth
      url: http://localhost:2504