server:
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: Ciaomondo123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

rsa:
  private-key: "classpath:certs/private.pem"
  public-key: "classpath:certs/public.pem"